sudo: false
language: cpp

compiler:
    - gcc

os:
    - linux
matrix:
    fast_finish: true
env:
    - CMAKE_BUILD_OPTIONS="-DWITH_NEL_TESTS:BOOL=off -DWITH_LUA51:BOOL=on -DWITH_LUA52:BOOL=off -DWITH_LUA53:BOOL=off"
    - CMAKE_BUILD_OPTIONS="-DWITH_NEL_TESTS:BOOL=off -DWITH_LUA51:BOOL=off -DWITH_LUA52:BOOL=on -DWITH_LUA53:BOOL=off"
    - CMAKE_BUILD_OPTIONS="-DWITH_NEL_TESTS:BOOL=off -DWITH_LUA51:BOOL=off -DWITH_LUA52:BOOL=off -DWITH_LUA53:BOOL=on"

addons:
    apt:
        packages:
            - liblua5.1-0-dev
            - liblua5.1-0-dbg
            - liblua5.2-0-dev
            - liblua5.2-0-dbg
            - libluabind-dev
            - libcpptest-dev
            - libogg-dev
            - libvorbis-dev
            - libopenal-dev
            - libgif-dev
            - libfreetype6-dev
            - libxml2-dev

before_script:
    - mkdir build
    - cmake --version

script:
    - cmake -Hcode -Bbuild $CMAKE_BUILD_OPTIONS
    - cmake --build build -- -j 2

notifications:
  irc:
    channels:
      - $NOTIFICATION_IRC_CHANNEL
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Description : %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
